apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque # default for arbitary key-value pairs
data: # storing data in a secret component doesn't, automatically make it secure
  mongo-username: c3VyZXNo # echo -n "suresh" | base64
  mongo-password: cGFzc3dvcmQ= # echo -n "password" | base64
  